const ACTIONS = {
  ADD_TRAINING: 'ADD_TRAINING',
  GET_TRAININGS: 'GET_TRAININGS',
  GET_TRAINING: 'GET_TRAINING',
  UPDATE_TRAINING: 'UPDATE_TRAINING',
  REMOVE_TRAINING: 'REMOVE_TRAINING',
  ADD_EXERCISE: 'ADD_EXERCISE',
  GET_EXERCISES: 'GET_EXERCISES',
  GET_EXERCISE: 'GET_EXERCISE',
  REMOVE_EXERCISE: 'REMOVE_EXERCISE',
  UPDATE_EXERCISE: 'UPDATE_EXERCISE',
  GET_TIMELINE_RAPORTS: 'GET_TIMELINE_RAPORTS',
  GET_TIMELINE_RAPORT: 'GET_TIMELINE_RAPORT',
  GET_SETTINGS: 'GET_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  GET_PROTEINS: 'GET_PROTEINS',
  ADD_PROTEIN: 'ADD_PROTEIN',
  UPDATE_PROTEIN: 'UPDATE_PROTEIN',
  REMOVE_PROTEIN: 'REMOVE_PROTEIN',
  GET_PROTEIN: 'GET_PROTEIN',
  DATA_PENDING: 'DATA_PENDING',
  REQUEST_ERROR: 'REQUEST_ERROR'
};

export default ACTIONS;